### ISSUE TITLE
Last semicolon missed in css

### ISSUE THREAD

**Issue by gubi** [wylst/atom-minifier#10]
The result of minimized css has no semicolon "`;`" before the closing parenthesis "`}`".
This will cause css malfunction when using the script minimized.

Obviously I checked the not-minimized source before open thi issue :)

Example:
```css
body > div.container {
	padding: 0;
}
```
becomes
```css
body>div.container{padding:0}
```
